// Auto-generated by prepare_data.py
`define NUM_SAMPLES 100
`define SCALE_SHIFT 10
`define KM_MAX 2360457
`define YR_MIN 1983
`define YR_MAX 2020
`define W1 32'sd-4621
`define W2 32'sd1288
`define W3 32'sd-21014
`define W4 32'sd100609
`define B 32'sd-12643
